### ISSUE TITLE
A hole

### ISSUE THREAD

**Issue by scheib** [paulmecklenburg/svg2nc#1]
Thank you for your excellent svc to nc conversion software. However, when applying the result to HDPE I found an unexpected hole. Why does your software make a hole? ![img_20141230_120918438](https://cloud.githubusercontent.com/assets/386971/5585319/d7fa2ce2-9075-11e4-968b-0bcc45d72cbb.jpg)
It made 12 holes, in 12 identical instances, however in 5 it did not.

**Comment by paulmecklenburg** [comment]
There was a tiny invalid artifact getting generated in the edge between the two layers. I changed to code to address this particular issue. In general it's safer to design the svg such that upper layers are a subset of lower layers (instead of disjoint).

https://github.com/paulmecklenburg/svg2nc/commit/5ef01cad7c2823295faf23f21cb1c5410a5103eb

**Comment by scheib** [comment]
Excellent work. I am excited there will be no more holes. I am sure to recommend this software to anyone who doesn't want holes. Also, I will recommend layers to be subsets of each other, especially when holes are not desired.
